<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SAIs-MacBook-Air.local" failures="1" tests="4" name="com.tutorialsninja.qa.testcases.LoginTest" time="82.808" errors="0" timestamp="2023-07-31T11:50:40 IST" skipped="0">
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyWithValidCredentails" time="19.627"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyWithInvalidCredentials" time="23.112">
    <failure message="expected:&lt;WWarning: No match for E-Mail Address and/or Password.&gt; but was:&lt;Warning: No match for E-Mail Address and/or Password.&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<WWarning: No match for E-Mail Address and/or Password.> but was:<Warning: No match for E-Mail Address and/or Password.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at com.tutorialsninja.qa.testcases.LoginTest.verifyWithInvalidCredentials(LoginTest.java:117)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyWithInvalidCredentials -->
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyWithValidMailAndInvalidPassword" time="21.846"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyWithInvalidMailAndValidPassword" time="18.223"/>
  <system-out/>
</testsuite> <!-- com.tutorialsninja.qa.testcases.LoginTest -->
